name: CI

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup env
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Dependency resolve
        run: |
          go mod download

      - name: Run tests
        run: |
          go test -race ./...